### ISSUE TITLE
_capsule doesn't build

### ISSUE THREAD

**Issue by gabor-ig** [jebw/jekyll-gemini#1]
I've been waiting for something like this, thank you so much! 
When I try executing jekyll gemini, I get
` fatal: 'jekyll gemini' could not be found. You may need to install the jekyll-gemini gem or a related gem to be able to use this subcommand. `
_capsule doesn't get built. I followed your instructions to the letter... are not all versions of jekyll compatible? Thanks!

**Comment by joshbeard** [comment]
Try it with Jekyll 4.x.

Example in Gemfile:

```plain
gem 'jekyll', '~> 4.2', '>= 4.2.2'
```

I encountered the same problem you did, which was resolved by running `bundle exec jekyll gemini`, however, that resulted in another issue that was resolved by ensuring I was using Jekyll 4 and not 3.

**Comment by krydos** [comment]
having the same issue. I'm on Jekyll 4.3
It looks like Jekyll just won't see the plugin. `gemini` command isn't registered, no files appear in `_capsule` folder

**Comment by lizsugar** [comment]
Chiming in to say yes I'm having the same issue with Jekyll 4.3.1

Here's the output when trying:

```
> bundle exec jekyll gemini --trace                                                                                             

Configuration file: $MASKED_DIR/_config.yml
            Source: $MASKED_DIR
       Destination: $MASKED_DIR/_capsule
 Incremental build: disabled. Enable with --incremental
      Generating...
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:228:in `assign_highlighter_options!': undefined method `highlighter_prefix' for nil:NilClass (NoMethodError)

      payload["highlighter_prefix"] = converters.first.highlighter_prefix
                                                      ^^^^^^^^^^^^^^^^^^^
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:57:in `run'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:578:in `render_regenerated'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:563:in `block (2 levels) in render_docs'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:562:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:562:in `block in render_docs'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:561:in `each_value'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:561:in `render_docs'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:210:in `render'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:80:in `process'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:28:in `process_site'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-gemini-0.1.0/lib/jekyll_gemini/command.rb:44:in `build'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-gemini-0.1.0/lib/jekyll_gemini/command.rb:30:in `process'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-gemini-0.1.0/lib/jekyll_gemini/command.rb:15:in `block (2 levels) in init_with_program'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.3.1/exe/jekyll:15:in `<top (required)>'
        from C:/Ruby31-x64/bin/jekyll:25:in `load'
        from C:/Ruby31-x64/bin/jekyll:25:in `<main>'
```

**Comment by lizsugar** [comment]
Okay ignore that post, I didn't read the documentation close enough, specifically

> This relies on the source files using Gemtext instead of Markdown, which are converted automatically via the Jekyll-Gemtext.
> 
> Any Gemtext files will be converted to HTML in _site via the usual jekyll build command.
> 
> A _capsule folder can also be generated by running jekyll gemini - only Static files and Gemtext source files are included - markdown Pages and Documents are ignored.

Clearing out all my markdown files and putting in some super basic gemini text files, and it works perfectly.  Will keep playing with this.  Thank you!  

Hopefully my inability to read helps someone else :)
